# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c27b9f4793902a92b6b69b26770e6d6f09eb62482aec69d70ac28b4c5f3b4f0363efb81abb041deba25afd2f3878b7b0c4e708662d01dc50bfec8920d57b645

test:
  secret_key_base: bd4e48103213586e2619992e94601ff84190a33b997457218e64db64cf1e8467042f8a9d7cc72fa6cb1c3560e1be11779bc154c32c86f440d2bd57e7fd25fcaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
